import type { Role } from "./types";

export const roles: Role[] = [
	{
		year: "2026",
		title: "Lead Software Engineer",
		org: "Cyberhill Partners",
		summary:
			"After a stint at Ultra Intelligence & Communications splitting a Django/React monolith into microservices, I now lead Wolverine — a self-healing cybersecurity knowledge-graph platform — which our team took from proof of concept to an agentic AI product on AWS Marketplace.",
		area: "ai",
		highlights: [
			"Set up the workflow that twenty contributors and their AI coding agents share: a 117-target Makefile as the single entry point, trunk-based development, and conventions that keep the code self-documenting.",
			"Streaming AI chat over WebSockets with Redis keeping tokens in order, and GraphRAG that turns plain English into openCypher and SPARQL.",
		],
		tech: [
			"django",
			"react",
			"typescript",
			"neptune",
			"bedrock",
			"graphrag",
			"websockets",
			"celery",
			"github-actions",
			"playwright",
			"terraform",
			"aws",
		],
	},
	{
		year: "2024",
		title: "Software Engineer (contract)",
		org: "Skaion Corporation",
		summary:
			"Government R&D work in a fully offline environment: a Django and React app with 2D/3D graph visualizations, and an on-prem AI service running a local GPT4All model queued through Celery and Redis. Briefed Department of Defense stakeholders, which helped secure further funding.",
		area: "infra",
		highlights: [
			"Refactored the Django backend into modular Python command-line scripts as requirements changed, so each processing step runs and is reused on its own.",
			"A local GPT4All service generating QEMU virtual machine commands under strict memory limits, queued through Celery and Redis.",
		],
		tech: [
			"django",
			"react",
			"python",
			"docker",
			"celery",
			"redis",
			"qemu",
			"bash",
		],
	},
	{
		year: "2023",
		title: "Founder",
		org: "Easy Covers Software",
		summary:
			"Founded an AI recruiting platform and built it from scratch: Django, Flask and Next.js microservices, call transcription with Whisper, LLM-generated notes, and ML match scores. Wrote the business plan and pitched it to venture capital firms.",
		area: "backend",
		highlights: [
			"Twilio calls transcribed with Whisper, notes generated by LLMs, and match scores that read what candidates said rather than only their resumes.",
			"A 25-page business plan and pitches that earned meetings with venture capitalists.",
		],
		tech: [
			"django",
			"flask",
			"nextjs",
			"postgresql",
			"whisper",
			"nginx",
			"docker",
			"aws",
		],
	},
	{
		year: "2022",
		title: "Software Engineer",
		org: "Forum Systems",
		summary:
			"First engineer hired onto Quantum Sim, an AI healthcare app that later spun out as its own company. Started on React, ended up building Django APIs, an NLP contract-analysis pipeline, and the deployments behind a Blue Cross Blue Shield engagement.",
		area: "frontend",
		highlights: [
			"An NLP pipeline that scores contract risk from PDF text with Word2Vec embeddings, Transformer models and GPT.",
			"Helped win Blue Cross Blue Shield follow-on funding for three more developers, then onboarded them with 25+ shell shortcuts.",
		],
		tech: ["react", "django", "django-rest-framework", "nlp", "bash", "linux"],
	},
	{
		year: "2021",
		title: "B.S. Psychology, then Columbia's web development bootcamp",
		org: "UMass Amherst and Columbia University",
		summary:
			"Graduated with a neuroscience concentration and a computer science minor, then went straight into Columbia's full-stack web development bootcamp.",
		area: "frontend",
		highlights: [
			"Neuroscience concentration and a computer science minor, with coursework in data structures, systems and computational theory.",
		],
		tech: [],
	},
	{
		year: "2020",
		title: "Research assistant",
		org: "Kwak Laboratory, UMass Amherst",
		summary:
			"Built an R pipeline that turned free-text survey responses about the 2018 midterms into structured data and classified them by emotion, showing how framing words shaped voter sentiment.",
		area: "ai",
		highlights: [],
		tech: ["nlp"],
	},
];
