import type { AreaInfo, Technology } from "./types";

export const areas: AreaInfo[] = [
	{ id: "backend", label: "Backend", token: "--area-backend" },
	{ id: "frontend", label: "Frontend", token: "--area-frontend" },
	{ id: "ai", label: "AI & data", token: "--area-ai" },
	{ id: "infra", label: "Infrastructure", token: "--area-infra" },
];

export const technologies: Technology[] = [
	{
		id: "python",
		label: "Python",
		area: "backend",
		weight: 3,
		links: ["django", "fastapi", "flask", "celery", "pytest"],
	},
	{
		id: "django",
		label: "Django",
		area: "backend",
		weight: 3,
		links: ["postgresql", "celery", "django-rest-framework", "websockets"],
	},
	{
		id: "django-rest-framework",
		label: "Django REST Framework",
		area: "backend",
		weight: 2,
		links: ["rest-apis"],
	},
	{
		id: "fastapi",
		label: "FastAPI",
		area: "backend",
		weight: 2,
		links: ["rest-apis"],
	},
	{
		id: "flask",
		label: "Flask",
		area: "backend",
		weight: 1,
		links: ["microservices"],
	},
	{
		id: "celery",
		label: "Celery",
		area: "backend",
		weight: 2,
		links: ["redis"],
	},
	{
		id: "websockets",
		label: "WebSockets",
		area: "backend",
		weight: 2,
		links: ["redis"],
	},
	{
		id: "rest-apis",
		label: "REST APIs",
		area: "backend",
		weight: 2,
		links: ["microservices"],
	},
	{
		id: "microservices",
		label: "Microservices",
		area: "backend",
		weight: 2,
		links: ["docker"],
	},
	{
		id: "pytest",
		label: "pytest",
		area: "backend",
		weight: 1,
		links: ["github-actions"],
	},
	{
		id: "react",
		label: "React",
		area: "frontend",
		weight: 3,
		links: ["typescript", "nextjs", "tanstack-query", "redux", "vite"],
	},
	{
		id: "typescript",
		label: "TypeScript",
		area: "frontend",
		weight: 3,
		links: ["nextjs", "playwright"],
	},
	{
		id: "nextjs",
		label: "Next.js",
		area: "frontend",
		weight: 2,
		links: ["tailwind"],
	},
	{
		id: "vite",
		label: "Vite",
		area: "frontend",
		weight: 1,
		links: ["tailwind"],
	},
	{
		id: "tanstack-query",
		label: "TanStack Query",
		area: "frontend",
		weight: 1,
		links: ["rest-apis"],
	},
	{
		id: "redux",
		label: "Redux",
		area: "frontend",
		weight: 1,
		links: ["material-ui"],
	},
	{
		id: "tailwind",
		label: "Tailwind CSS",
		area: "frontend",
		weight: 2,
		links: ["design-systems"],
	},
	{
		id: "material-ui",
		label: "Material UI",
		area: "frontend",
		weight: 1,
		links: ["design-systems"],
	},
	{
		id: "design-systems",
		label: "Design systems",
		area: "frontend",
		weight: 2,
		links: [],
	},
	{
		id: "playwright",
		label: "Playwright",
		area: "frontend",
		weight: 2,
		links: ["github-actions"],
	},
	{
		id: "bedrock",
		label: "AWS Bedrock",
		area: "ai",
		weight: 2,
		links: ["graphrag", "langchain", "llm-guardrails", "aws"],
	},
	{
		id: "langchain",
		label: "LangChain",
		area: "ai",
		weight: 2,
		links: ["graphrag", "agentic-ai"],
	},
	{
		id: "graphrag",
		label: "GraphRAG",
		area: "ai",
		weight: 2,
		links: ["neptune", "neo4j", "opencypher"],
	},
	{
		id: "agentic-ai",
		label: "Agentic AI",
		area: "ai",
		weight: 2,
		links: ["llm-guardrails"],
	},
	{
		id: "llm-guardrails",
		label: "LLM guardrails",
		area: "ai",
		weight: 1,
		links: [],
	},
	{
		id: "nlp",
		label: "NLP",
		area: "ai",
		weight: 2,
		links: ["whisper", "python"],
	},
	{ id: "whisper", label: "Whisper", area: "ai", weight: 1, links: [] },
	{
		id: "postgresql",
		label: "PostgreSQL",
		area: "ai",
		weight: 3,
		links: ["redis"],
	},
	{ id: "neo4j", label: "Neo4j", area: "ai", weight: 2, links: ["opencypher"] },
	{
		id: "neptune",
		label: "Amazon Neptune",
		area: "ai",
		weight: 2,
		links: ["opencypher", "sparql", "aws"],
	},
	{ id: "redis", label: "Redis", area: "ai", weight: 2, links: [] },
	{
		id: "opencypher",
		label: "openCypher",
		area: "ai",
		weight: 1,
		links: ["sparql"],
	},
	{ id: "sparql", label: "SPARQL", area: "ai", weight: 1, links: [] },
	{
		id: "aws",
		label: "AWS",
		area: "infra",
		weight: 3,
		links: ["terraform", "cloudformation", "docker", "cloudwatch"],
	},
	{
		id: "terraform",
		label: "Terraform",
		area: "infra",
		weight: 2,
		links: ["cloudformation"],
	},
	{
		id: "cloudformation",
		label: "CloudFormation",
		area: "infra",
		weight: 2,
		links: [],
	},
	{
		id: "docker",
		label: "Docker",
		area: "infra",
		weight: 2,
		links: ["github-actions", "jenkins", "nginx"],
	},
	{
		id: "github-actions",
		label: "GitHub Actions",
		area: "infra",
		weight: 2,
		links: ["jenkins"],
	},
	{ id: "jenkins", label: "Jenkins", area: "infra", weight: 1, links: [] },
	{
		id: "linux",
		label: "Linux",
		area: "infra",
		weight: 2,
		links: ["qemu", "bash", "nginx"],
	},
	{ id: "bash", label: "Bash", area: "infra", weight: 2, links: ["python"] },
	{ id: "qemu", label: "QEMU", area: "infra", weight: 1, links: [] },
	{ id: "nginx", label: "Nginx", area: "infra", weight: 1, links: [] },
	{
		id: "opentelemetry",
		label: "OpenTelemetry",
		area: "infra",
		weight: 1,
		links: ["prometheus", "grafana"],
	},
	{
		id: "prometheus",
		label: "Prometheus",
		area: "infra",
		weight: 1,
		links: ["grafana"],
	},
	{ id: "grafana", label: "Grafana", area: "infra", weight: 1, links: [] },
	{
		id: "cloudwatch",
		label: "CloudWatch",
		area: "infra",
		weight: 1,
		links: ["grafana"],
	},
];
